In [2]:
import torch

In [3]:
print(torch.cuda.is_available())

False


In [4]:
print(torch.rand(2, 2))

tensor([[0.1356, 0.2029],
        [0.9551, 0.5796]])


## Tensors

In [5]:
# creating tensor from list
x = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [7]:
# changing an element in tensor using standard python
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [8]:
# special creation functions to generate particular types of tensors
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.ones(1, 2) + torch.ones(1, 2)

tensor([[2., 2.]])

In [11]:
torch.rand(1).item()

0.927113950252533

In [13]:
# tensors can live in cpu or gpus
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [15]:
# gpu_tensor = cpu_tensor.to("cuda")
# gpu_tensor.device

### Tensor Operations

In [16]:
torch.rand(2, 2).max()

tensor(0.8427)

In [17]:
torch.rand(2, 2).max().item()

0.8683673739433289

In [19]:
# sometimes need to change the dtype of the tensor
long_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
long_tensor.type()

'torch.LongTensor'

In [20]:
float_tensor = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

inplace operations can be done by adding `underscore` at the end of the method applied on tensor


In [22]:
# reshaping tensors
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [23]:
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

Rearranging dimensions of a tensor 
eg: images often stored as `[height, width, channels]` but pytorch prefers to deal with `[channels, height, width]`  
`permute()` can be used to deal with these in a fairly straighforward manner

In [24]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 640, 480])

### Tensor Broadcasting

two tensors can be broadcasted if 
* two dimensions are equal 
* one of the dimension is one 